# Generated by Django 6.0.3 on 2026-03-20 11:46

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=martor.models.MartorField(),
        ),
    ]
