# Generated by Django 5.2.13 on 2026-04-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0010_articlerevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Bản nháp"),
                    ("pending", "Chờ duyệt"),
                    ("published", "Đã xuất bản"),
                    ("rejected", "Bị từ chối"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
