# Generated by Django 5.2.13 on 2026-04-22 12:55

import django.db.models.deletion
import wiki.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0013_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Bản nháp"),
                    ("pending", "Chờ duyệt"),
                    ("published", "Đã xuất bản"),
                    ("rejected", "Bị từ chối"),
                    ("needs_edit", "Yêu cầu sửa đổi"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CodingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("allowed_languages", models.JSONField(blank=True, default=list)),
                ("default_language", models.CharField(blank=True, max_length=32)),
                ("starter_code_map", models.JSONField(blank=True, default=dict)),
                (
                    "time_limit_ms",
                    models.PositiveIntegerField(
                        default=wiki.models.default_coding_time_limit
                    ),
                ),
                (
                    "memory_limit_mb",
                    models.PositiveIntegerField(
                        default=wiki.models.default_coding_memory_limit
                    ),
                ),
                (
                    "compare_mode",
                    models.CharField(
                        choices=[
                            ("exact", "Khá»›p tuyá»‡t Ä‘á»‘i"),
                            (
                                "trim_lines",
                                "Bá»\x8f khoáº£ng tráº¯ng Ä‘áº§u/cuá»‘i má»—i dÃ²ng",
                            ),
                            ("tokenized", "So sá»›p theo token"),
                        ],
                        default="trim_lines",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_exercise",
                        to="wiki.article",
                    ),
                ),
            ],
            options={
                "ordering": ["article_id"],
            },
        ),
        migrations.CreateModel(
            name="CodingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=32)),
                ("source_code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("compile_error", "Compile Error"),
                            ("runtime_error", "Runtime Error"),
                            ("time_limit_exceeded", "Time Limit Exceeded"),
                            ("internal_error", "Internal Error"),
                            ("running", "Running"),
                        ],
                        default="running",
                        max_length=32,
                    ),
                ),
                ("compile_output", models.TextField(blank=True)),
                ("stdout_preview", models.TextField(blank=True)),
                ("stderr_preview", models.TextField(blank=True)),
                ("custom_input", models.TextField(blank=True)),
                ("is_sample_run", models.BooleanField(default=False)),
                ("total_tests", models.PositiveIntegerField(default=0)),
                ("passed_tests", models.PositiveIntegerField(default=0)),
                ("runtime_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="wiki.codingexercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodingTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("input_text", models.TextField(blank=True)),
                ("expected_output_text", models.TextField(blank=True)),
                (
                    "input_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=wiki.models.coding_case_upload_to,
                        validators=[wiki.models.testcase_file_validator],
                    ),
                ),
                (
                    "expected_output_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=wiki.models.coding_case_upload_to,
                        validators=[wiki.models.testcase_file_validator],
                    ),
                ),
                ("is_sample", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("score", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testcases",
                        to="wiki.codingexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CodingSubmissionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_name", models.CharField(max_length=120)),
                ("status", models.CharField(max_length=32)),
                ("runtime_ms", models.PositiveIntegerField(default=0)),
                ("stdout_preview", models.TextField(blank=True)),
                ("stderr_preview", models.TextField(blank=True)),
                ("expected_preview", models.TextField(blank=True)),
                ("actual_preview", models.TextField(blank=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="wiki.codingsubmission",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_results",
                        to="wiki.codingtestcase",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
