# Generated by Django 5.2.13 on 2026-04-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0014_alter_article_status_codingexercise_codingsubmission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageRuntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=64)),
                ("monaco", models.CharField(default="plaintext", max_length=32)),
                ("source", models.CharField(max_length=64)),
                ("compile_cmd", models.JSONField(blank=True, default=list)),
                ("run_cmd", models.JSONField(default=list)),
                ("starter", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=100)),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.AlterField(
            model_name="codingexercise",
            name="compare_mode",
            field=models.CharField(
                choices=[
                    ("exact", "Exact match"),
                    ("trim_lines", "Trim whitespace"),
                    ("tokenized", "Token-based"),
                ],
                default="trim_lines",
                max_length=20,
            ),
        ),
    ]
