# Generated by Django 5.2.13 on 2026-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0015_languageruntime_alter_codingexercise_compare_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="codingexercise",
            name="checker_code",
            field=models.TextField(
                blank=True,
                help_text="Mã nguồn giám khảo chấm bài (dùng cho Custom Checker)",
            ),
        ),
        migrations.AddField(
            model_name="codingexercise",
            name="checker_language",
            field=models.CharField(
                blank=True,
                help_text="Ngôn ngữ của mã nguồn giám khảo (ví dụ: python, cpp)",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="codingsubmission",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="codingsubmission",
            name="subtask_results",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="codingtestcase",
            name="subtask_id",
            field=models.PositiveIntegerField(
                default=1,
                help_text="ID của subtask (các testcase cùng ID sẽ gom lại thành 1 subtask)",
            ),
        ),
        migrations.AlterField(
            model_name="codingexercise",
            name="compare_mode",
            field=models.CharField(
                choices=[
                    ("exact", "Exact match"),
                    ("trim_lines", "Trim whitespace"),
                    ("tokenized", "Token-based"),
                    ("custom_checker", "Custom Checker"),
                ],
                default="trim_lines",
                max_length=20,
            ),
        ),
    ]
