# Generated by Django 5.2.14 on 2026-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_codingexercise_checker_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Bật để khóa quyền tương tác (bình luận, viết bài, vote) của người dùng.'),
        ),
    ]
