# Generated by Django 5.2.14 on 2026-06-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_article_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Học sinh'), ('teacher', 'Giáo viên'), ('moderator', 'Người kiểm duyệt')], default='student', help_text='Vai trò của người dùng trên hệ thống.', max_length=20),
        ),
        migrations.AlterField(
            model_name='codingsubmission',
            name='status',
            field=models.CharField(choices=[('accepted', 'Chấp nhận'), ('wrong_answer', 'Sai kết quả'), ('compile_error', 'Lỗi biên dịch'), ('runtime_error', 'Lỗi thực thi'), ('time_limit_exceeded', 'Quá giới hạn thời gian'), ('internal_error', 'Lỗi hệ thống'), ('running', 'Đang chấm bài')], default='running', max_length=32),
        ),
    ]
