[uwsgi]
# Project-specific settings
project = config
base = /var/www/site

# Paths
chdir = %(base)
module = %(project).wsgi:application
home = %(base)/venv

# Process-related settings
master = true
processes = 4
threads = 2

# Communication
socket = /run/uwsgi/%(project).sock
chown-socket = www-data:www-data
chmod-socket = 660
vacuum = true

# Logging
logto = /var/log/uwsgi/%(project).log

# Environment variables
env = DJANGO_SETTINGS_MODULE=%(project).settings
env = PYTHONIOENCODING=UTF-8
